services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ze_brands_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: unless-stopped
    env_file:
      - ./env/local.env
    depends_on:
      - db
    volumes:
      - ./:/app:cached
    ports:
      - "${DEV_PORT:-8083}:8083"
    command: ["/bin/bash","-c","/app/scripts/entrypoint.sh"]

volumes:
  postgres_data:
