from enum import Enum


class ErrorCodeEnum(str, Enum):
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ALREADY_EXIST_USER = "ALREADY_EXIST_USER"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    ALREADY_EXIST_BRAND_NAME = "ALREADY_EXIST_BRAND_NAME"

    ALREADY_EXIST_PRODUCT_SKU = "ALREADY_EXIST_PRODUCT_SKU"
    BRAND_NOT_FOUND = "BRAND_NOT_FOUND"
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
